---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install python3-debian for deb822_repository module
      ansible.builtin.apt:
        name: python3-debian
        state: present
        update_cache: true
